#!/bin/bash

# ==============================================================================
# Collect MPAS NMC perturbation samples for SABER/BUMP training
# ------------------------------------------------------------------------------
#
# This script collects the PTB_f48mf24.nc products generated by
# prepare_nmc_samples.sh and creates a sequential set of symbolic links:
#
#   PTB_f48mf24_001.nc
#   PTB_f48mf24_002.nc
#   ...
#
# These links can be consumed directly by the subsequent VBAL/HDIAGS/NICAS
# calibration stages.
#
# No NetCDF data are copied.
#
# Usage:
#
#   ./collect_samples.sh
#
# or:
#
#   NMC_ROOT=/path/to/nmc_samples ./collect_samples.sh
#
# ROOT may also be supplied as the first positional argument:
#
#   ./collect_samples.sh /path/to/nmc_samples
#
# ==============================================================================

ROOT="${1:-${NMC_ROOT:-${HOME}/jedi/nmc_samples}}"

OUTDIR="${ROOT}/output"
SAMPLES="${ROOT}/samples"

if [ ! -d "${OUTDIR}" ]; then
  echo "FAILED: NMC output directory not found: ${OUTDIR}"
  return 1 2>/dev/null || false
fi

mkdir -p "${SAMPLES}"
rm -f "${SAMPLES}"/PTB_f48mf24_*.nc

i=0

while IFS= read -r f; do
  d="$(basename "$(dirname "${f}")")"

  # Accept only complete NMC pairs.  The perturbation must have been produced
  # from a directory containing both corresponding FULL states.
  [ -s "${OUTDIR}/${d}/FULL_f24.nc" ] || continue
  [ -s "${OUTDIR}/${d}/FULL_f48.nc" ] || continue
  [ -s "${f}" ] || continue

  i=$((i + 1))

  ln -sfn "${f}" \
    "${SAMPLES}/PTB_f48mf24_$(printf '%03d' "${i}").nc"

done < <(
  find "${OUTDIR}" \
    -mindepth 2 \
    -maxdepth 2 \
    -type f \
    -name 'PTB_f48mf24.nc' \
    | sort
)

echo
echo "Prepared NMC samples in: ${SAMPLES}"
echo "Number of samples: ${i}"

if [ "${i}" -eq 0 ]; then
  echo "FAILED: no complete PTB_f48mf24 samples found"
  return 1 2>/dev/null || false
fi

echo
echo "First samples:"
ls -lh "${SAMPLES}"/PTB_f48mf24_*.nc | head

echo
echo "Last samples:"
ls -lh "${SAMPLES}"/PTB_f48mf24_*.nc | tail

echo
echo "Sample pattern for SABER/BUMP:"
echo "  ${SAMPLES}/PTB_f48mf24_*.nc"
